In [1]:
# CHI-SQUARE TEST
# Association between Device Type and Customer Satisfaction

# Background:
# Mizzare Corporation has collected data on customer satisfaction levels 
# for two types of smart home devices: Smart Thermostats and Smart Lights. 
# They want to determine if there's a significant association between the 
# type of device purchased and the customer's satisfaction level.


In [2]:
# Data Provided:
# The data is summarized in a contingency table showing the counts of customers
# in each satisfaction level for both types of devices:

In [3]:
# Step1:Import required libraries
import pandas as pd
df=pd.read_csv(r"customer satisfaction levels.csv")
df



Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70
5             Total               240          360    600

In [4]:
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency

# Read the data from the table without considering total value
observed_values = df.iloc[0:5:,[1,2]].values
observed_values

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]], dtype=int64)

In [5]:
# find out expected_values using chi2_contingency()
val=stats.chi2_contingency(observed_values)
expected_values=val[3]
expected_values

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [6]:
# degree of freedom
no_of_rows=len(df.iloc[0:5,0])
no_of_cloumns=len(df.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_cloumns-1)

In [7]:
# calculate chi_square
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square

array([3.38293651, 2.25529101])

In [8]:
# calculate chi_square_statastic
chi_square_statastic=chi_square[0]+chi_square[1]
chi_square_statastic

5.638227513227513

In [9]:
# Calculate the critical_value using chi2.ppf()
alpha = 0.05
critical_value=chi2.ppf(q=1-alpha,df=ddof)
critical_value

9.487729036781154

In [10]:
if chi_square_statastic >= critical_value:
    print("Reject Null Hypothesis")
else:
    print("Retain Null Hypothesis")

Retain Null Hypothesis


In [11]:
# Conclusion:
# There's a significant association between 
# the type of device purchased and the customer's satisfaction level.